### ISSUE TITLE
chests break slowly

### ISSUE THREAD

**Issue by tenshiiclone** [LieOnLion/More-Chest-Varient#22]
the chests from this mod take about twice as long as normal chests to break with an axe

**To Reproduce**
place down mcv chest
try to break chest with axe
takes about twice as long

**Expected behavior**
mcv chests break in normal chest breaking speed

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Mod Version: 1.5.8
 - Mod loader: neoforge
 - Mod loader version: 21.2.72

**Comment by lieonlion** [comment]
Fix is easy, should be able to get it done today.

**Comment by lieonlion** [comment]
Fixed with version 1.5.9:

[Modrinth](https://modrinth.com/mod/more-chest-variants-lieonlion/version/H9TwIeCP)
[Curseforge](https://www.curseforge.com/minecraft/mc-mods/more-chest-variants-lieonlion/files/5862569)
