### ISSUE TITLE
Can't place chest on Llama or similar entity

### ISSUE THREAD

**Issue by cserjay** [LieOnLion/More-Chest-Varient#24]
**Describe the bug** **required*
Unable to put chest on llama, donkey or camels

**To Reproduce**
1. Tame a llama, donkey or a camel
2. Try to put oak chest to tamed llama
3. Unable to put chest unless using the default chest (vanilla) which isn't available for crafting etc..

**Expected behavior**
Can put variant chest.. it's ok if using default entity chest texture

**Screenshots**
![2024-11-06_10 00 16](https://github.com/user-attachments/assets/f63aeab2-4b5d-4c3b-8770-25bdd256d8d1)

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Mod Version: 1.5.6
 - Mod loader: Fabric
 - Mod loader version: 

**Additional context**
N/A

**Comment by lieonlion** [comment]
can you not craft a regular chest by putting one of the variant chests in a crafting table?
