### ISSUE TITLE
Broken textures on some trapped chests

### ISSUE THREAD

**Issue by Exludus** [LieOnLion/More-Chest-Varient#26]
**Describe the bug** **required*
Some textures for trapped chests are broken on version 1.19.2

**To Reproduce**
Load game
Missing textures for trapped variants of Oak, Acacia, Dark Oak, Mangrove, and Warped chests

**Expected behavior**
For the mod to not have missing textures.

**Screenshots**
![2024-11-16_21 49 08](https://github.com/user-attachments/assets/8e354a2f-ac71-435d-a440-36dc8acb41b3)

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Mod Version: 1.5.0-beta.2
 - Mod loader: Forge
 - Mod loader version: 43.4.0

**Additional context**

The mod list I had when I ran into this issue.

Additional Structures 
Another Furniture 
Architectury 
AutoRegLib 
Better Combat 
Biomes O' Plenty 
Blueprint 
Bookshelf 
Caelus API 
Canary 
Chunky 
Citadel 
Cloth Config v8 API 
Clumps 
Cobweb 
Collective 
Comforts 
Compat O' Plenty 
Connectedness 
Controlling 
CoroUtil 
Corpse 
Crafting Automat 
Curios API 
Double Doors 
Dynamic Lights 
Elytra Slot 
Embeddium 
EnchantmentDescriptions 
EntityCulling 
Every Compat 
Ferrite Core 
From The Fog 
GeckoLib 
Guard Villagers 
HT's TreeChop 
Let Me Despawn 
Memory Leak Fix 
Mob Battle Mod 
Mobtimizations 
Model Gap Fix 
ModernFix 
Moonlight Library 
More Chest Variants 
More Mob Variants 
Mouse Tweaks 
Nyf's Spiders 2.0 
Oculus 
Particular 
Player Animator 
Polymorph 
Puzzles Lib 
Quad 
Random Crits 
Reforgium 
Respawning Animals 
Roughly Enough Items (REI) 
Simple Weapons 
Sophisticated Backpacks 
Sophisticated Core 
Soul Fire'd 
Soulbound 
Sound Physics Remastered 
Spyglass Improvements 
Stalker Creepers 
Starlight 
Structory 
Structory: Towers 
Tectonic 
TerraBlender 
The Blind Wanderer 
The One Who Watches 
The Root of Fear 
Towns and Towers 
True Darkness 
Variant Crafting Tables 
Vertical Slabs Compat 
Woodworks 
figure

**Comment by lieonlion** [comment]
I am no longer supporting versions below 1.20 at the current time.
